pandoc --from html --to rst < aboutauthor.html > aboutauthor.rst
pandoc --from html --to rst < arithexp.html > arithexp.rst
pandoc --from html --to rst < arrays.html > arrays.rst
pandoc --from html --to rst < asciitable.html > asciitable.rst
pandoc --from html --to rst < assortedtips.html > assortedtips.rst
pandoc --from html --to rst < authorsnote.html > authorsnote.rst
pandoc --from html --to rst < awk.html > awk.rst
pandoc --from html --to rst < bash2.html > bash2.rst
pandoc --from html --to rst < bash-options.html > bash-options.rst
pandoc --from html --to rst < bashver2.html > bashver2.rst
pandoc --from html --to rst < bashver3.html > bashver3.rst
pandoc --from html --to rst < bashver4.html > bashver4.rst
pandoc --from html --to rst < basic.html > basic.rst
pandoc --from html --to rst < biblio.html > biblio.rst
pandoc --from html --to rst < colorizing.html > colorizing.rst
pandoc --from html --to rst < command-line-options.html > command-line-options.rst
pandoc --from html --to rst < commandsub.html > commandsub.rst
pandoc --from html --to rst < communications.html > communications.rst
pandoc --from html --to rst < comparison-ops.html > comparison-ops.rst
pandoc --from html --to rst < complexfunct.html > complexfunct.rst
pandoc --from html --to rst < contributed-scripts.html > contributed-scripts.rst
pandoc --from html --to rst < copyright.html > copyright.rst
pandoc --from html --to rst < credits.html > credits.rst
pandoc --from html --to rst < dblparens.html > dblparens.rst
pandoc --from html --to rst < debugging.html > debugging.rst
pandoc --from html --to rst < declareref.html > declareref.rst
pandoc --from html --to rst < devproc.html > devproc.rst
pandoc --from html --to rst < devref1.html > devref1.rst
pandoc --from html --to rst < disclaimer.html > disclaimer.rst
pandoc --from html --to rst < dosbatch.html > dosbatch.rst
pandoc --from html --to rst < endnotes.html > endnotes.rst
pandoc --from html --to rst < escapingsection.html > escapingsection.rst
pandoc --from html --to rst < exercises.html > exercises.rst
pandoc --from html --to rst < exitcodes.html > exitcodes.rst
pandoc --from html --to rst < exit-status.html > exit-status.rst
pandoc --from html --to rst < external.html > external.rst
pandoc --from html --to rst < extmisc.html > extmisc.rst
pandoc --from html --to rst < filearchiv.html > filearchiv.rst
pandoc --from html --to rst < files.html > files.rst
pandoc --from html --to rst < fto.html > fto.rst
pandoc --from html --to rst < functions.html > functions.rst
pandoc --from html --to rst < globbingref.html > globbingref.rst
pandoc --from html --to rst < gotchas.html > gotchas.rst
pandoc --from html --to rst < here-docs.html > here-docs.rst
pandoc --from html --to rst < histcommands.html > histcommands.rst
pandoc --from html --to rst < index.html > index.rst
pandoc --from html --to rst < intandnonint.html > intandnonint.rst
pandoc --from html --to rst < internal.html > internal.rst
pandoc --from html --to rst < internalvariables.html > internalvariables.rst
pandoc --from html --to rst < invoking.html > invoking.rst
pandoc --from html --to rst < io-redirection.html > io-redirection.rst
pandoc --from html --to rst < ioredirintro.html > ioredirintro.rst
pandoc --from html --to rst < ivr.html > ivr.rst
pandoc --from html --to rst < list-cons.html > list-cons.rst
pandoc --from html --to rst < localization.html > localization.rst
pandoc --from html --to rst < localvar.html > localvar.rst
pandoc --from html --to rst < loopcontrol.html > loopcontrol.rst
pandoc --from html --to rst < loops1.html > loops1.rst
pandoc --from html --to rst < loops.html > loops.rst
pandoc --from html --to rst < manipulatingvars.html > manipulatingvars.rst
pandoc --from html --to rst < mathc.html > mathc.rst
pandoc --from html --to rst < mirrorsites.html > mirrorsites.rst
pandoc --from html --to rst < miscellany.html > miscellany.rst
pandoc --from html --to rst < moreadv.html > moreadv.rst
pandoc --from html --to rst < nestedifthen.html > nestedifthen.rst
pandoc --from html --to rst < nestedloops.html > nestedloops.rst
pandoc --from html --to rst < networkprogramming.html > networkprogramming.rst
pandoc --from html --to rst < numerical-constants.html > numerical-constants.rst
pandoc --from html --to rst < operations.html > operations.rst
pandoc --from html --to rst < opprecedence.html > opprecedence.rst
pandoc --from html --to rst < ops.html > ops.rst
pandoc --from html --to rst < optimizations.html > optimizations.rst
pandoc --from html --to rst < options.html > options.rst
pandoc --from html --to rst < othertypesv.html > othertypesv.rst
pandoc --from html --to rst < parameter-substitution.html > parameter-substitution.rst
pandoc --from html --to rst < part1.html > part1.rst
pandoc --from html --to rst < part2.html > part2.rst
pandoc --from html --to rst < part3.html > part3.rst
pandoc --from html --to rst < part4.html > part4.rst
pandoc --from html --to rst < part5.html > part5.rst
pandoc --from html --to rst < pathmanagement.html > pathmanagement.rst
pandoc --from html --to rst < portabilityissues.html > portabilityissues.rst
pandoc --from html --to rst < prelimexer.html > prelimexer.rst
pandoc --from html --to rst < process-sub.html > process-sub.rst
pandoc --from html --to rst < procref1.html > procref1.rst
pandoc --from html --to rst < quoting.html > quoting.rst
pandoc --from html --to rst < quotingvar.html > quotingvar.rst
pandoc --from html --to rst < randomvar.html > randomvar.rst
pandoc --from html --to rst < recess-time.html > recess-time.rst
pandoc --from html --to rst < recurnolocvar.html > recurnolocvar.rst
pandoc --from html --to rst < recursionsct.html > recursionsct.rst
pandoc --from html --to rst < redirapps.html > redirapps.rst
pandoc --from html --to rst < redircb.html > redircb.rst
pandoc --from html --to rst < refcards.html > refcards.rst
pandoc --from html --to rst < regexp.html > regexp.rst
pandoc --from html --to rst < restricted-sh.html > restricted-sh.rst
pandoc --from html --to rst < revisionhistory.html > revisionhistory.rst
pandoc --from html --to rst < sample-bashrc.html > sample-bashrc.rst
pandoc --from html --to rst < scriptanalysis.html > scriptanalysis.rst
pandoc --from html --to rst < scrstyle.html > scrstyle.rst
pandoc --from html --to rst < securityissues.html > securityissues.rst
pandoc --from html --to rst < sedawk.html > sedawk.rst
pandoc --from html --to rst < sha-bang.html > sha-bang.rst
pandoc --from html --to rst < special-chars.html > special-chars.rst
pandoc --from html --to rst < standard-options.html > standard-options.rst
pandoc --from html --to rst < string-manipulation.html > string-manipulation.rst
pandoc --from html --to rst < subshells.html > subshells.rst
pandoc --from html --to rst < sysscripts.html > sysscripts.rst
pandoc --from html --to rst < systemdirs.html > systemdirs.rst
pandoc --from html --to rst < system.html > system.rst
pandoc --from html --to rst < tabexpansion.html > tabexpansion.rst
pandoc --from html --to rst < terminalccmds.html > terminalccmds.rst
pandoc --from html --to rst < testbranch.html > testbranch.rst
pandoc --from html --to rst < testconstructs.html > testconstructs.rst
pandoc --from html --to rst < testsandcomparisons.html > testsandcomparisons.rst
pandoc --from html --to rst < tests.html > tests.rst
pandoc --from html --to rst < testtest.html > testtest.rst
pandoc --from html --to rst < textproc.html > textproc.rst
pandoc --from html --to rst < timedate.html > timedate.rst
pandoc --from html --to rst < todolist.html > todolist.rst
pandoc --from html --to rst < toolsused.html > toolsused.rst
pandoc --from html --to rst < unofficialst.html > unofficialst.rst
pandoc --from html --to rst < untyped.html > untyped.rst
pandoc --from html --to rst < varassignment.html > varassignment.rst
pandoc --from html --to rst < variables2.html > variables2.rst
pandoc --from html --to rst < variables.html > variables.rst
pandoc --from html --to rst < varsubn.html > varsubn.rst
pandoc --from html --to rst < wherehelp.html > wherehelp.rst
pandoc --from html --to rst < why-shell.html > why-shell.rst
pandoc --from html --to rst < winscript.html > winscript.rst
pandoc --from html --to rst < wrapper.html > wrapper.rst
pandoc --from html --to rst < writingscripts.html > writingscripts.rst
pandoc --from html --to rst < x17129.html > x17129.rst
pandoc --from html --to rst < x17837.html > x17837.rst
pandoc --from html --to rst < x17974.html > x17974.rst
pandoc --from html --to rst < x23170.html > x23170.rst
pandoc --from html --to rst < x9644.html > x9644.rst
pandoc --from html --to rst < xrefindex.html > xrefindex.rst
pandoc --from html --to rst < zeros.html > zeros.rst
