pandoc --from html --to rst --parse-raw < aboutauthor.html > aboutauthor.rst
pandoc --from html --to rst --parse-raw < arithexp.html > arithexp.rst
pandoc --from html --to rst --parse-raw < arrays.html > arrays.rst
pandoc --from html --to rst --parse-raw < asciitable.html > asciitable.rst
pandoc --from html --to rst --parse-raw < assortedtips.html > assortedtips.rst
pandoc --from html --to rst --parse-raw < authorsnote.html > authorsnote.rst
pandoc --from html --to rst --parse-raw < awk.html > awk.rst
pandoc --from html --to rst --parse-raw < bash2.html > bash2.rst
pandoc --from html --to rst --parse-raw < bash-options.html > bash-options.rst
pandoc --from html --to rst --parse-raw < bashver2.html > bashver2.rst
pandoc --from html --to rst --parse-raw < bashver3.html > bashver3.rst
pandoc --from html --to rst --parse-raw < bashver4.html > bashver4.rst
pandoc --from html --to rst --parse-raw < basic.html > basic.rst
pandoc --from html --to rst --parse-raw < biblio.html > biblio.rst
pandoc --from html --to rst --parse-raw < colorizing.html > colorizing.rst
pandoc --from html --to rst --parse-raw < command-line-options.html > command-line-options.rst
pandoc --from html --to rst --parse-raw < commandsub.html > commandsub.rst
pandoc --from html --to rst --parse-raw < communications.html > communications.rst
pandoc --from html --to rst --parse-raw < comparison-ops.html > comparison-ops.rst
pandoc --from html --to rst --parse-raw < complexfunct.html > complexfunct.rst
pandoc --from html --to rst --parse-raw < contributed-scripts.html > contributed-scripts.rst
pandoc --from html --to rst --parse-raw < copyright.html > copyright.rst
pandoc --from html --to rst --parse-raw < credits.html > credits.rst
pandoc --from html --to rst --parse-raw < dblparens.html > dblparens.rst
pandoc --from html --to rst --parse-raw < debugging.html > debugging.rst
pandoc --from html --to rst --parse-raw < declareref.html > declareref.rst
pandoc --from html --to rst --parse-raw < devproc.html > devproc.rst
pandoc --from html --to rst --parse-raw < devref1.html > devref1.rst
pandoc --from html --to rst --parse-raw < disclaimer.html > disclaimer.rst
pandoc --from html --to rst --parse-raw < dosbatch.html > dosbatch.rst
pandoc --from html --to rst --parse-raw < endnotes.html > endnotes.rst
pandoc --from html --to rst --parse-raw < escapingsection.html > escapingsection.rst
pandoc --from html --to rst --parse-raw < exercises.html > exercises.rst
pandoc --from html --to rst --parse-raw < exitcodes.html > exitcodes.rst
pandoc --from html --to rst --parse-raw < exit-status.html > exit-status.rst
pandoc --from html --to rst --parse-raw < external.html > external.rst
pandoc --from html --to rst --parse-raw < extmisc.html > extmisc.rst
pandoc --from html --to rst --parse-raw < filearchiv.html > filearchiv.rst
pandoc --from html --to rst --parse-raw < files.html > files.rst
pandoc --from html --to rst --parse-raw < fto.html > fto.rst
pandoc --from html --to rst --parse-raw < functions.html > functions.rst
pandoc --from html --to rst --parse-raw < globbingref.html > globbingref.rst
pandoc --from html --to rst --parse-raw < gotchas.html > gotchas.rst
pandoc --from html --to rst --parse-raw < here-docs.html > here-docs.rst
pandoc --from html --to rst --parse-raw < histcommands.html > histcommands.rst
pandoc --from html --to rst --parse-raw < index.html > index.rst
pandoc --from html --to rst --parse-raw < intandnonint.html > intandnonint.rst
pandoc --from html --to rst --parse-raw < internal.html > internal.rst
pandoc --from html --to rst --parse-raw < internalvariables.html > internalvariables.rst
pandoc --from html --to rst --parse-raw < invoking.html > invoking.rst
pandoc --from html --to rst --parse-raw < io-redirection.html > io-redirection.rst
pandoc --from html --to rst --parse-raw < ioredirintro.html > ioredirintro.rst
pandoc --from html --to rst --parse-raw < ivr.html > ivr.rst
pandoc --from html --to rst --parse-raw < list-cons.html > list-cons.rst
pandoc --from html --to rst --parse-raw < localization.html > localization.rst
pandoc --from html --to rst --parse-raw < localvar.html > localvar.rst
pandoc --from html --to rst --parse-raw < loopcontrol.html > loopcontrol.rst
pandoc --from html --to rst --parse-raw < loops1.html > loops1.rst
pandoc --from html --to rst --parse-raw < loops.html > loops.rst
pandoc --from html --to rst --parse-raw < manipulatingvars.html > manipulatingvars.rst
pandoc --from html --to rst --parse-raw < mathc.html > mathc.rst
pandoc --from html --to rst --parse-raw < mirrorsites.html > mirrorsites.rst
pandoc --from html --to rst --parse-raw < miscellany.html > miscellany.rst
pandoc --from html --to rst --parse-raw < moreadv.html > moreadv.rst
pandoc --from html --to rst --parse-raw < nestedifthen.html > nestedifthen.rst
pandoc --from html --to rst --parse-raw < nestedloops.html > nestedloops.rst
pandoc --from html --to rst --parse-raw < networkprogramming.html > networkprogramming.rst
pandoc --from html --to rst --parse-raw < numerical-constants.html > numerical-constants.rst
pandoc --from html --to rst --parse-raw < operations.html > operations.rst
pandoc --from html --to rst --parse-raw < opprecedence.html > opprecedence.rst
pandoc --from html --to rst --parse-raw < ops.html > ops.rst
pandoc --from html --to rst --parse-raw < optimizations.html > optimizations.rst
pandoc --from html --to rst --parse-raw < options.html > options.rst
pandoc --from html --to rst --parse-raw < othertypesv.html > othertypesv.rst
pandoc --from html --to rst --parse-raw < parameter-substitution.html > parameter-substitution.rst
pandoc --from html --to rst --parse-raw < part1.html > part1.rst
pandoc --from html --to rst --parse-raw < part2.html > part2.rst
pandoc --from html --to rst --parse-raw < part3.html > part3.rst
pandoc --from html --to rst --parse-raw < part4.html > part4.rst
pandoc --from html --to rst --parse-raw < part5.html > part5.rst
pandoc --from html --to rst --parse-raw < pathmanagement.html > pathmanagement.rst
pandoc --from html --to rst --parse-raw < portabilityissues.html > portabilityissues.rst
pandoc --from html --to rst --parse-raw < prelimexer.html > prelimexer.rst
pandoc --from html --to rst --parse-raw < process-sub.html > process-sub.rst
pandoc --from html --to rst --parse-raw < procref1.html > procref1.rst
pandoc --from html --to rst --parse-raw < quoting.html > quoting.rst
pandoc --from html --to rst --parse-raw < quotingvar.html > quotingvar.rst
pandoc --from html --to rst --parse-raw < randomvar.html > randomvar.rst
pandoc --from html --to rst --parse-raw < recess-time.html > recess-time.rst
pandoc --from html --to rst --parse-raw < recurnolocvar.html > recurnolocvar.rst
pandoc --from html --to rst --parse-raw < recursionsct.html > recursionsct.rst
pandoc --from html --to rst --parse-raw < redirapps.html > redirapps.rst
pandoc --from html --to rst --parse-raw < redircb.html > redircb.rst
pandoc --from html --to rst --parse-raw < refcards.html > refcards.rst
pandoc --from html --to rst --parse-raw < regexp.html > regexp.rst
pandoc --from html --to rst --parse-raw < restricted-sh.html > restricted-sh.rst
pandoc --from html --to rst --parse-raw < revisionhistory.html > revisionhistory.rst
pandoc --from html --to rst --parse-raw < sample-bashrc.html > sample-bashrc.rst
pandoc --from html --to rst --parse-raw < scriptanalysis.html > scriptanalysis.rst
pandoc --from html --to rst --parse-raw < scrstyle.html > scrstyle.rst
pandoc --from html --to rst --parse-raw < securityissues.html > securityissues.rst
pandoc --from html --to rst --parse-raw < sedawk.html > sedawk.rst
pandoc --from html --to rst --parse-raw < sha-bang.html > sha-bang.rst
pandoc --from html --to rst --parse-raw < special-chars.html > special-chars.rst
pandoc --from html --to rst --parse-raw < standard-options.html > standard-options.rst
pandoc --from html --to rst --parse-raw < string-manipulation.html > string-manipulation.rst
pandoc --from html --to rst --parse-raw < subshells.html > subshells.rst
pandoc --from html --to rst --parse-raw < sysscripts.html > sysscripts.rst
pandoc --from html --to rst --parse-raw < systemdirs.html > systemdirs.rst
pandoc --from html --to rst --parse-raw < system.html > system.rst
pandoc --from html --to rst --parse-raw < tabexpansion.html > tabexpansion.rst
pandoc --from html --to rst --parse-raw < terminalccmds.html > terminalccmds.rst
pandoc --from html --to rst --parse-raw < testbranch.html > testbranch.rst
pandoc --from html --to rst --parse-raw < testconstructs.html > testconstructs.rst
pandoc --from html --to rst --parse-raw < testsandcomparisons.html > testsandcomparisons.rst
pandoc --from html --to rst --parse-raw < tests.html > tests.rst
pandoc --from html --to rst --parse-raw < testtest.html > testtest.rst
pandoc --from html --to rst --parse-raw < textproc.html > textproc.rst
pandoc --from html --to rst --parse-raw < timedate.html > timedate.rst
pandoc --from html --to rst --parse-raw < todolist.html > todolist.rst
pandoc --from html --to rst --parse-raw < toolsused.html > toolsused.rst
pandoc --from html --to rst --parse-raw < unofficialst.html > unofficialst.rst
pandoc --from html --to rst --parse-raw < untyped.html > untyped.rst
pandoc --from html --to rst --parse-raw < varassignment.html > varassignment.rst
pandoc --from html --to rst --parse-raw < variables2.html > variables2.rst
pandoc --from html --to rst --parse-raw < variables.html > variables.rst
pandoc --from html --to rst --parse-raw < varsubn.html > varsubn.rst
pandoc --from html --to rst --parse-raw < wherehelp.html > wherehelp.rst
pandoc --from html --to rst --parse-raw < why-shell.html > why-shell.rst
pandoc --from html --to rst --parse-raw < winscript.html > winscript.rst
pandoc --from html --to rst --parse-raw < wrapper.html > wrapper.rst
pandoc --from html --to rst --parse-raw < writingscripts.html > writingscripts.rst
pandoc --from html --to rst --parse-raw < x17129.html > x17129.rst
pandoc --from html --to rst --parse-raw < x17837.html > x17837.rst
pandoc --from html --to rst --parse-raw < x17974.html > x17974.rst
pandoc --from html --to rst --parse-raw < x23170.html > x23170.rst
pandoc --from html --to rst --parse-raw < x9644.html > x9644.rst
pandoc --from html --to rst --parse-raw < xrefindex.html > xrefindex.rst
pandoc --from html --to rst --parse-raw < zeros.html > zeros.rst
pandoc --from html --to rst --parse-raw < aliases.html > aliases.rst

